import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cp, mkdir, readFile } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// --- Helper Functions ---

async function getObsidianDir() {
  try {
    const env = JSON.parse(await readFile("env.json", "utf8"));
    return env.OBSIDIAN_PLUGIN_DIR;
  } catch (err) {
    console.warn("env.json not found or invalid. Skipping sync to Obsidian directory.");
    return null;
  }
}

// --- esbuild Plugins ---

// Copies the final build artifacts to the Obsidian plugin directory
const copyStaticAssetsPlugin = {
  name: "copy-static-assets",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;
      if (!existsSync("dist")) await mkdir("dist");
      await cp("manifest.json", "dist/manifest.json");
    });
  },
};

const syncToObsidianPlugin = (obsidianDir) => ({
  name: "sync-to-obsidian",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0 || !obsidianDir) return;
      if (!existsSync(obsidianDir)) await mkdir(obsidianDir, { recursive: true });

      const filesToSync = [
        { from: "dist/main.js", to: "main.js" },
        { from: "dist/styles.css", to: "styles.css" },
        { from: "dist/manifest.json", to: "manifest.json" },
      ];

      for (const file of filesToSync) {
        const srcPath = path.resolve(file.from);
        const destPath = path.resolve(path.join(obsidianDir, file.to));

        if (srcPath !== destPath) {
          await cp(srcPath, destPath);
          console.log(`Synced ${srcPath} -> ${destPath}`);
        }
      }
      console.log(`✅ Sync complete to ${obsidianDir}`);
    });
  },
});


// --- Main Build Process ---

(async () => {
  const obsidianDir = await getObsidianDir();

  const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts", "src/styles/styles.css"],
    bundle: true,
    external: ["obsidian", "electron", ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: "dist",
    entryNames: "[name]",
    minify: prod,
    plugins: [
      copyStaticAssetsPlugin,
      syncToObsidianPlugin(obsidianDir),
    ],
  });

  if (prod) {
    await context.rebuild();
    process.exit(0);
  } else {
    await context.watch();
  }
})();
